name: 'Magento 2 PhpStan'
author: 'ExtDN'
description: 'performs php static code analysis with the Magento 2 PhpStan ruleset'
inputs:
  composer_name:
    description: 'Your composer name. Example: foo/magento2-bar'
    required: true
  module_source:
    description: 'Relative path to your module source within your repository. Empty by default.'
    required: false
  phpstan_level:
    description: 'PHPStan level to check. 1 by default.'
    default: "1"
    required: false
  composer_version:
    description: 'The composer version to use. Can be either 1 or 2.'
    required: false
    default: "2"
  magento_pre_install_script:
    description: 'Relative path to an optional script before Magento installation is run. Leave empty to use the default.'
    required: false
runs:
  using: 'docker'
  image: 'docker://extdn/magento-phpstan-action:latest'
branding:
  icon: 'code'  
  color: 'red'
