name: ExtDN Integration Tests
on: [push]

jobs:
  integration-tests:
    name: Magento 2 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping"
    env:
      MODULE_NAME: ${{ secrets.MODULE_NAME }}
      COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-integration-tests/7.3@master
        env:
          MAGENTO_VERSION: '2.3.7-p3'
      - uses: extdn/github-actions-m2/magento-integration-tests/7.4@master
        env:
          MAGENTO_VERSION: '2.4.3-p2'
      - uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        env:
          MAGENTO_VERSION: '2.4.4'
      - uses: extdn/github-actions-m2/magento-integration-tests/8.2@master
        env:
          MAGENTO_VERSION: '2.4.6-p3'
      - uses: extdn/github-actions-m2/magento-integration-tests/8.3@master
        env:
          MAGENTO_VERSION: '2.4.7'
      - uses: extdn/github-actions-m2/magento-integration-tests/8.4@master
        env:
          MAGENTO_VERSION: '2.4.8'
