name: ExtDN PHPStan
on: [push]

jobs:
  phpstan:
    name: Static Code Analysis with PHPStan
    runs-on: ubuntu-latest
    env:
      COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
      PHPSTAN_LEVEL: 2
      COMPOSER_VERSION: 2
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-phpstan/8.3@master
